apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1-container
          image: kre1/app1:PLACEHOLDER # Jenkins will replace this
          imagePullPolicy: Always
          ports:
            - containerPort: 80 # Assuming App2 also runs on port 80
---
apiVersion: v1
kind: Service
metadata:
  name: app1-service
spec:
  type: NodePort
  selector:
    app: app1
  ports:
    - port: 80
      targetPort: 80 # Assuming App2 also targets port 80
      nodePort: 30005 